name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  matrix:
    strategy:
      matrix:
        os-version: [ ubuntu-latest, windows-latest ]
        go-version: [ 'stable', '1.22' ]
        
    runs-on: ${{matrix.os-version}}
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go ${{matrix.go-version}}
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.go-version}}

    - name: Build exampleservice
      run: go build -v github.com/image357/password/cmd/exampleservice
    - name: Build patchheader
      run: go build -v github.com/image357/password/cmd/patchheader
    - name: Build recovery tool
      run: go build -v github.com/image357/password/cmd/recovery
    - name: Build cinterface
      run: go build -buildmode=c-shared -o ./cinterface/ -v github.com/image357/password/cinterface
    - name: Test password
      run: go test -v github.com/image357/password
    - name: Test rest
      run: go test -v github.com/image357/password/rest
      
