# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build exampleservice
      run: go build -v github.com/image357/password/cmd/exampleservice
    - name: Build patchheader
      run: go build -v github.com/image357/password/cmd/patchheader
    - name: Build cinterface
      run: go build -buildmode=c-shared -o ./cinterface/ -v github.com/image357/password/cinterface
    - name: Test password
      run: go test -v github.com/image357/password
    - name: Test rest
      run: go test -v github.com/image357/password/rest
      
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build exampleservice
      run: go build -v github.com/image357/password/cmd/exampleservice
    - name: Build patchheader
      run: go build -v github.com/image357/password/cmd/patchheader
    - name: Build cinterface
      run: go build -buildmode=c-shared -o ./cinterface/ -v github.com/image357/password/cinterface
    - name: Test password
      run: go test -v github.com/image357/password
    - name: Test rest
      run: go test -v github.com/image357/password/rest
      
